### ISSUE TITLE
blender 3.4 ver addon install error

### ISSUE THREAD

**Issue by Dongkit96** [NevilArt/BsMax#32]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\stayn\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\BsMax-master\__init__.py", line 48, in <module>
    from .keymaps import register_keymaps, unregister_keymaps
ImportError: cannot import name 'register_keymaps' from 'BsMax-master.keymaps' (unknown location)

hi. how can fixed it?

**Comment by hurricanz** [comment]
I confirm.  this doesn't work

**Comment by NevilArt** [comment]
Hi.
Are you sure you use the right version of BsMax?
If Blender 3.4 do not work with last update of BsMax .

1. Remove BsMax.
2. Rest factory the Blender.
3. Install BsMax again and reopen Blender.

It most work. currently I`m working with Blender 3.4 and works fine.

Please test this and let me know if it works.

**Comment by Dongkit96** [comment]
oh! thank you! it works!! it's fine.
i think.... download recent & right bs max & blender 3.4 .
why did't worked?? just error??
